baseURL = 'https://scippy.cat/'
languageCode = "en"
defaultContentLanguage = "en"
title = 'Scippy'
theme = 'KeepIt'


paginate = 12
enableEmoji = true
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 4

[params]
    since = 2023
    author = "Scrippy"               # Author's name
    subtitle = ""       # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other
    dateFormatToUse = "" # set date format, default "2 January 2006"

    avatar = "/images/me/avatar.jpeg" #comment it to use gravatar
    socialShare = true

    description = "" # site description
    keywords = "" # site keywords

    license= 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
    defaultPage = "/posts/"


[params.social]
    Instagram = "xxxx"
   

[params.share]
Instagram = true
Twitter = true
Facebook = true
Douban = true
Weibo = true

# Used only for Seo schema
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[author]
  name = "Fastbyte01"

  [params.publisher]
    name = "Fastbyte01"

    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40

  [params.logo]
    url = "logo.png"
    width = 127
    height = 40

  [params.image]
    url = "cover.png"
    width = 800
    height = 600
